### ISSUE TITLE
Sass 学习与使用

### ISSUE THREAD

**Issue by tiantingrui** [tiantingrui/daily-harvest#1]
# Sass 

## 什么是Sass?

1. Sass 是一个CSS 预处理器
2. Sass 是CSS 扩展语言，可以帮助我们减少CSS代码，节省开发时间
3. Sass 完全兼容所有版本的CSS

## Sass 特性
1. 扩展了CSS3, 增加了
   1. 规则
   2. 变量
   3. 混入
   4. 选择器
   5. 继承
   6. 内置函数等等特性
2. Sass 生成良好格式化的CSS 代码，易于组织和维护
3. Sass 文件后缀为 `.scss`

举个例子：
```scss
// 定义变量与值
$bgcolor: lightblue;
$textcolor: darkblue;
$fontsize: 18px;

// 使用变量
body {
  background-color: $bgcolor;
  color: $textcolor;
  font-size: $fontsize;
}

```

## Sass 变量
变量用于存储一些信息，它可以重复使用

Sass变量可以存储以下信息：
1. 字符串
2. 数字
3. 颜色值
4. 布尔值
5. 列表
6. null 值

**Sass 变量使用 `$` 符号**
```scss
// 定义变量与值
$bgcolor: lightblue;
$textcolor: darkblue;
$fontsize: 18px;
$myFont: Helvetica, sans-serif;
$myColor: red;
$myFontSize: 18px;
$myWidth: 680px;
```

## Sass 作用域
Sass 变量的作用域只能在当前的层级上有效果，如下所示 h1 的样式为它内部定义的 green，p 标签则是为 red。
```scss
$myColor: red;

h1 {
  $myColor: green;   // 只在 h1 里头有用，局部作用域
  color: $myColor;
}

p {
  color: $myColor;
}
```
```css
h1 {
  color: green;
}

p {
  color: red;
}
```

#### !global 设置变量是全局的
```scss
$myColor: red;

h1 {
  $myColor: green !global;  // 全局作用域
  color: $myColor;
}

p {
  color: $myColor;
}
```
```css
h1 {
  color: green;
}

p {
  color: green;
}
```
**注意：所有的全局变量我们一般定义在同一个文件，如：_globals.scss，然后我们使用 @include 来包含该文件。**

## Sass 嵌套规则与属性
Sass 嵌套 CSS 选择器类似于 HTML 的嵌套规则。
如下我们嵌套一个导航栏的样式：
```scss
nav {
  ul {
    margin: 0;
    padding: 0;
    list-style: none;
  }
  li {
    display: inline-block;
  }
  a {
    display: block;
    padding: 6px 12px;
    text-decoration: none;
  }
}
```

```css
nav ul {
  margin: 0;
  padding: 0;
  list-style: none;
}
nav li {
  display: inline-block;
}
nav a {
  display: block;
  padding: 6px 12px;
  text-decoration: none;
}
```

**Sass 嵌套属性**
很多 CSS 属性都有同样的前缀，例如：font-family, font-size 和 font-weight ， text-align, text-transform 和 text-overflow。

在 Sass 中，我们可以使用嵌套属性来编写它们：
```scss
font: {
  family: Helvetica, sans-serif;
  size: 18px;
  weight: bold;
}

text: {
  align: center;
  transform: lowercase;
  overflow: hidden;
}
```

```css
font-family: Helvetica, sans-serif;
font-size: 18px;
font-weight: bold;

text-align: center;
text-transform: lowercase;
text-overflow: hidden;
```

## Sass @import 
**Sass 导入文件**
类似 CSS，Sass 支持 @import 指令。
@import 指令可以让我们导入其他文件等内容。
CSS @import 指令在每次调用时，都会创建一个额外的 HTTP 请求。但，Sass @import 指令将文件包含在 CSS 中，不需要额外的 HTTP 请求。

Sass @import 指令语法如下：
```
@import filename
```
**注意：包含文件时不需要指定文件后缀，Sass会自动添加 `.scss`**
此外，你也可以导入 CSS 文件。
导入后我们就可以在主文件中使用导入文件等变量。
以下实例，导入 variables.scss、colors.scss 和 reset.scss 文件。
```scss
@import "variables";
@import "colors";
@import "reset";
```
创建reset.scss文件
```scss
html,
body,
ul,
ol {
  margin: 0;
  padding: 0;
}

```
然后我们在 index.scss 文件中使用 @import 指令导入 reset.scss 文件：
```scss
@import "reset";

body {
  font-family: Helvetica, sans-serif;
  font-size: 18px;
  color: red;
}
```
```css
html, body, ul, ol {
  margin: 0;
  padding: 0;
}

body {
  font-family: Helvetica, sans-serif;
  font-size: 18px;
  color: red;
}
```

## @mixin 与 @include
1. @mixin 指令允许我们定义一个可以在整个样式表中重复使用的样式。
2. @include指令可以将混入（mixin） 引入到文档中。

### 定义一个混入
混入(mixin)通过 @mixin 指令来定义。 @mixin name { property: value; property: value; ... }
以下实例创建一个名为 "important-text" 的混入：
```scss
@mixin important-text {
  color: red;
  font-size: 25px;
  font-weight: bold;
  border: 1px solid blue;
}

```
**注意**：Sass 的连接符号 - 与下划线符号 _ 是相同的，也就是 @mixin important-text { } 与 @mixin important_text { } 是一样的混入。

#### 使用混入
@include 指令课用于包含一混入：
```scss
.danger {
  @include important-text;
  background-color: green;
}
```
```css
.danger {
  color: red;
  font-size: 25px;
  font-weight: bold;
  border: 1px solid blue;
  background-color: green;
}
```

混入中也可以包含混入：
```scss
@mixin special-text {
  @include inportant-text;
  @include link;
  @include special-border;
}
```

### 向 混入传递变量
1. 混入可以接收参数
2. 我们 可以向混入传递变量
3. 定义可以接收参数的混入

```scss
// 混入接收两个参数
@mixin bordered($color, $width) {
  border: $width solid $color;
}

// 调用混入，并传递两个参数
.myArticle {
  @include bordered(blue, 1px)
}
.myNotes {
  @include bordered(red, 2px)

}
```

```css
.myArticle {
  border: 1px solid blue;
}

.myNotes {
  border: 2px solid red;
}
```
混入的参数也可以定义默认值，语法格式如下：
```scss
@mixin bordered($color: blue, $width: 1px) {
  border: $width solid $color;
}
```
在包含混入时，你只需要传递需要的变量名及其值：
```scss
@mixin sexy-border($color, $width: 1in) {
  border: {
    color: $color;
    width: $width;
    style: dashed;
  }
}
p { @include sexy-border(blue); }
h1 { @include sexy-border(blue, 2in); }
```
```css
p {
  border-color: blue;
  border-width: 1in;
  border-style: dashed; }

h1 {
  border-color: blue;
  border-width: 2in;
  border-style: dashed;
}
```

### 可变参数
```scss
@mixin box-shadow($shadows...) {
      -moz-box-shadow: $shadows;
      -webkit-box-shadow: $shadows;
      box-shadow: $shadows;
}

.shadows {
  @include box-shadow(0px 4px 5px #666, 2px 6px 10px #999);
}

```

```css
.shadows {
  -moz-box-shadow: 0px 4px 5px #666, 2px 6px 10px #999;
  -webkit-box-shadow: 0px 4px 5px #666, 2px 6px 10px #999;
  box-shadow: 0px 4px 5px #666, 2px 6px 10px #999;
}
```

## @extend 与 继承
@extend 指令告诉 Sass 一个选择器的样式从另一选择器继承。

如果一个样式与另外一个样式几乎相同，只有少量的区别，则使用 @extend 就显得很有用。

以下 Sass 实例中，我们创建了一个基本的按钮样式 .button-basic，接着我们定义了两个按钮样式 .button-report 与 .button-submit，它们都继承了 .button-basic ，它们主要区别在于背景颜色与字体颜色，其他的样式都是一样的。

```scss
.button-basic  {
  border: none;
  padding: 15px 30px;
  text-align: center;
  font-size: 16px;
  cursor: pointer;
}

.button-report  {
  @extend .button-basic;
  background-color: red;
}

.button-submit  {
  @extend .button-basic;
  background-color: green;
  color: white;
}
```

```css
.button-basic, .button-report, .button-submit {
  border: none;
  padding: 15px 30px;
  text-align: center;
  font-size: 16px;
  cursor: pointer;
}

.button-report  {
  background-color: red;
}

.button-submit  {
  background-color: green;
  color: white;
}
```

使用 @extend 后，我们在 HTML 按钮标签中就不需要指定多个类 class="button-basic button-report" ，只需要设置 class="button-report" 类就好了。

@extend 很好的体现了**代码的复用**。
