### ISSUE TITLE
css 隐藏滚动条，但是依旧可以滚动

### ISSUE THREAD

**Issue by tiantingrui** [tiantingrui/daily-harvest#30]
自定义滚动条的伪对象选择器::-webkit-scrollbar。
不支持IE

```css
.element::-webkit-scrollbar { width: 0 !important }
```
